[package]
name = "set_version"
version = "0.1.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
description = "A small tool for setting a new version across all splatter crates."
edition = "2018"

[[bin]]
name = "set_version"
path = "main.rs"

[dependencies]
semver = "1.0"
toml_edit = "0.1"
